version: '3.5'
services:
    backend:
        build:
            context: ./
            dockerfile: Dockerfile
        image: ship-api:latest
        ports:
            - 5000:80
        environment:
            - ConnectionStrings__DefaultString=Host=ep-lively-cell-444164.ap-southeast-1.aws.neon.tech;Port=5432;User ID=daufather;Password=j1oMbqZ6EGfI;Database=neondb;;
        command: ["dotnet", "ef", "database update"]
        networks:
            - my-network
networks:
    my-network:
        driver: bridge