version: '3.5'
services:
    backend:
        depends_on:
            - postgres-database
        image: dcms-api:latest
        ports:
            - 80:80
            - 443:443
        environment:
            - ConnectionStrings__DefaultString=Host=localhost;Port=5432;User ID=test;Password=KBt8Pd2d7dXVSUvkbdD7;Database=testShip;
            - Logging__LogLevel__Default=Information
            - Logging__LogLevel__Microsoft.AspNetCore=Warning
        command: ["dotnet", "ef", "database update"]
        networks:
            my-network-name:
                aliases:
                    - dcms-api
    postgres-database:
        container_name: postgres_container
        image: postgres:12.13
        environment:
            POSTGRES_DB: testShip
            POSTGRES_USER: dcmsAdmin
            POSTGRES_PASSWORD: KBt8Pd2d7dXVSUvkbdD7
            PGDATA: /var/lib/postgresql/data
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            my-network-name:
                aliases:
                    - postgres-name
        restart: unless-stopped
volumes:
    db-data:
networks:
    my-network-name: